export const CLIENT_ID = "NVCONY5JSLT2NGSKTB5HSNTVGI1CYQ2PLVPHIFX3P2OMRZ3L";
export const CLIENT_SECRET ="WPTEKUUQ21VLIR4QMHRQZXYRBKGOKG1U4LZGDVW2KQPJRPA2";
export const MAPS_KEY="AIzaSyA2EGewCQz-uAHXThAurrTggHQjXckiH3o";
